Refactor CI release workflows
- Rename the current release workflows to "legacy"
- Remove build step from create-release workflow, so it can reuse the build
artifacts from other jobs
- Validate legacy release "side" param earlier
- Enable "strict mode" for all CI shell scripts
- Add new release workflow

diff --git a/.github/workflows/create-legacy-release.yml b/.github/workflows/create-legacy-release.yml
--- a/.github/workflows/create-legacy-release.yml
+++ b/.github/workflows/create-legacy-release.yml
@@ -1,12 +1,12 @@
 # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 
-name: Publish release
+name: Create legacy release
 
 on:
   workflow_call:
     inputs:
       target:
-        description: "The git ref to checkout, build from and release"
+        description: "The git commit to be associated with the release"
         required: true
         type: string
       tag:
@@ -66,14 +66,8 @@ env:
     Lua
 
 jobs:
-  build:
-    uses: ./.github/workflows/build.yml
-    with:
-      target: ${{ inputs.target }}
-
-  publish-release:
+  create-legacy-release:
     runs-on: ubuntu-latest
-    needs: [build]
     steps:
       - name: Download build artifacts
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
@@ -83,6 +77,7 @@ jobs:
 
       - name: Extract build artifacts
         run: |
+          set -Eeuo pipefail
           artifacts_dir="$(realpath -m "$CI_DIR/artifacts")"
           mkdir -p "$artifacts_dir"
           tar -xzf "$CI_DIR/build.tar.gz" -C "$artifacts_dir"
@@ -90,7 +85,7 @@ jobs:
 
       - name: Create archives
         run: |
-          set -e
+          set -Eeuo pipefail
           shopt -s globstar nullglob
           shopt -u dotglob
 
@@ -107,16 +102,29 @@ jobs:
           lines_to_array RELEASES
 
           artifacts_dir="$(realpath -m "$CI_DIR/artifacts")"
-          mkdir -p "$artifacts_dir"
-
           archives_dir="$(realpath -m "$CI_DIR/archives")"
           mkdir -p "$archives_dir"
 
           for i in "${!RELEASES[@]}"; do
             [[ -z "${RELEASES[i]}" ]] && continue
             (
-              IFS=':' read platform side publish_dir _rest <<< "${RELEASES[i]}"
+              IFS=':' read -r platform side publish_dir _rest <<< "${RELEASES[i]}"
               cd "${artifacts_dir}/${publish_dir}"
+
+              if [[ "$side" == "client" ]]; then
+                patch_files=(
+                  ${ARCHIVE_FILES_SHARED[@]}
+                  ${ARCHIVE_FILES_CLIENT[@]}
+                )
+              elif [[ "$side" == "server" ]]; then
+                patch_files=(
+                  ${ARCHIVE_FILES_SHARED[@]}
+                  ${ARCHIVE_FILES_SERVER[@]}
+                )
+              else
+                echo "::error::invalid side: $side"
+                exit 1
+              fi
 
               echo "Creating build_${platform}_${side}.zip"
               zip --must-match -qr "${archives_dir}/${ARCHIVE_BASE_NAME}_build_${platform}_${side}.zip" *
@@ -126,37 +134,22 @@ jobs:
                 --owner=0 --group=0 \
                 *
 
-              if [[ "$side" == "client" ]]; then
-                files=(
-                  ${ARCHIVE_FILES_SHARED[@]}
-                  ${ARCHIVE_FILES_CLIENT[@]}
-                )
-              elif [[ "$side" == "server" ]]; then
-                files=(
-                  ${ARCHIVE_FILES_SHARED[@]}
-                  ${ARCHIVE_FILES_SERVER[@]}
-                )
-              else
-                echo "Invalid side: $side"
-                exit 1
-              fi
-
               echo "Creating patch_${platform}_${side}.zip"
               zip \
                 --must-match \
                 -qr \
                 "${archives_dir}/${ARCHIVE_BASE_NAME}_patch_${platform}_${side}.zip" \
-                "${files[@]}"
+                "${patch_files[@]}"
 
               echo "Creating patch_${platform}_${side}.tar.gz"
               tar \
                 -zcf "${archives_dir}/${ARCHIVE_BASE_NAME}_patch_${platform}_${side}.tar.gz" \
                 --owner=0 --group=0 \
-                "${files[@]}"
+                "${patch_files[@]}"
             )
           done
 
-      - name: Publish release
+      - name: Create release
         uses: notpeelz/action-gh-create-release@a12edfc71daf5daa7922b931c28e2bf88d3b2ced # v5.0.0
         with:
           target: ${{ inputs.target }}
